export const options = () => {
  return {
    cargo: [
      { id: 0,  label: 'Sócio/CEO'},
      { id: 1,  label: 'Diretor'},
      { id: 2,  label: 'Gerente/Coordenador de Vendas'},
      { id: 3,  label: 'Gerente/Coordenador de Marketing'},
      { id: 4,  label: 'Analista'},
      { id: 5,  label: 'Estagiário/Estudante'},
      { id: 6,  label: 'Outros Cargos'},
    ],
    segmento: [
      { id: 0, label: 'Advocacia'},
      { id: 1, label: 'Agronegócio'},
      { id: 2, label: 'Alimentícia'},
      { id: 3, label: 'Auditoria'},
      { id: 4, label: 'Aviação'},
      { id: 5, label: 'Banco'},
      { id: 6, label: 'Construção Civil'},
      { id: 7, label: 'Construtora/Incorporadora'},
      { id: 8, label: 'Consultoria empresarial'},
      { id: 9, label: 'Cooperativa'},
      { id: 10, label: 'Corretora de valores'},
      { id: 11, label: 'E-commerce'},
      { id: 12, label: 'Educação'},
      { id: 13, label: 'Eletroeletrônicos'},
      { id: 14, label: 'Entretenimento'},
      { id: 15, label: 'Farmacêutica'},
      { id: 16, label: 'Fundo de investimento'},
      { id: 17, label: 'Governo'},
      { id: 18, label: 'Hospital/Saúde'},
      { id: 19, label: 'Hotelaria'},
      { id: 20, label: 'Indústria Automotiva'},
      { id: 21, label: 'Indústria Naval'},
      { id: 22, label: 'Indústria química'},
      { id: 23, label: 'Logística/transporte'},
      { id: 24, label: 'Meio de pagamento'},
      { id: 25, label: 'Mercado imobiliário'},
      { id: 26, label: 'Mineração/óleo/gás'},
      { id: 27, label: 'Papel e celulose'},
      { id: 28, label: 'Propaganda e marketing'},
      { id: 29, label: 'Recrutamento e seleção'},
      { id: 30, label: 'Seguradora'},
      { id: 31, label: 'Segurança'},
      { id: 32, label: 'Siderurgia'},
      { id: 33, label: 'Sindicatos'},
      { id: 34, label: 'Telecom/TV'},
      { id: 35, label: 'TI/Software'},
      { id: 36, label: 'Turismo/viagens'},
      { id: 37, label: 'Utilities - Energia e água'},
      { id: 38, label: 'Varejo'},
      { id: 39, label: 'Vestuário'},
      { id: 40, label: 'Prestação de Serviços'}
    ],
    ajuda: [
      { id: 0, label: 'Inteligência de mercado/Prospecção de clientes' },
      { id: 1, label: 'Análise de risco e prevenção de perdas' },
      { id: 2, label: 'Enriquecimento de dados' },
      { id: 3, label: 'Due diligence' },
      { id: 4, label: 'Recuperação de cobrança' },
      { id: 5, label: 'Monitoramento de diários oficiais' },
      { id: 6, label: 'Outros' },
    ],
  }
}